### ISSUE TITLE
Updating bound properties does not update icon

### ISSUE THREAD

**Issue by rmja** [jmzagorski/aurelia-fontawesome#5]
**I'm submitting a bug report**

* **Library Version:**
0.1.0

* **Browser:**
all
**Current behavior:**

Using the custom element with attributes bound to the viewmodel does not update the icon when the attributes are changed. For example:

```
<font-awesome-icon icon="coffee" spin.bind="doTheSpin"></font-awesome-icon>
```

The icon does not spin/stop-spinning depending on `doTheSpin`. It only reads the value of `doTheSpin` during activation of the view.

**What is the expected behavior?**
That the properties of the icon can be updated during the lifetime of the view model

**What is the motivation / use case for changing the behavior?**
I want to avoid having to `if.bind` the icons depending on the properties

**Comment by jmzagorski** [comment]
Thanks, this is a great request. This can be accomplished if I add the `propertyChanged` method called by Aurelia and recompile the view in the slot and remove the old one. Though it seems like a lot, it takes about 1 millisecond or so. The alternative would be to try and find and replace the class or style on the svg element using `this.$element.querySelector('svg')`. Though that might be slightly faster, i feel it is more prone to bugs since it is more code.

I will submit a PR soon

**Comment by rmja** [comment]
I like the simplicity of updating the class list on the svg element - however, it should also work on the icon property itself in which case the icon has to be regenerated.

**Comment by rmja** [comment]
I have made a proposal for a fix. If you have a different idea, feel free to reject it:-)

**Comment by jmzagorski** [comment]
I have not had time to revisit my PR or review yours, been doing too much SQL stuff the past few days. Hopefully I can work on this tomorrow and we can get the change in one PR that we both approve.

Then after that I can cut a release to npm for v0.2.0. I have not used this library in a production app yet which is why I am staying away from going v1.0

**Comment by jmzagorski** [comment]
See my latest commit on PR https://github.com/jmzagorski/aurelia-fontawesome/pull/8. I went a different direction after reviewing the code since all we are doing is using the html that is generated from the font awesome library and private `convert` method. Seems doing it this way is a lot easier and lets aurelia handle the html changes.

I ran a few memory snapshots in firefox and chrome and there is little to no memory changes between snapshots, but I will leave that PR open for you to review to see what you think.
